import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import PulsatingTriangles from "./components/pulsatingPyramids";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        style={{ position: "relative", overflow: "hidden" }} // Ensure the body is positioned relative for background control
      >
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: "100vw",
            height: "100vh",
            zIndex: -1, // Ensures it's behind all content
            overflow: "hidden",
          }}
        >
          <PulsatingTriangles />
        </div>

        {/* Main Content */}
        <div style={{ position: "relative", zIndex: 1 }}>{children}</div>
      </body>
    </html>
  );
}
